const DEFAULTS=[{name:'Hip Flexor Stretch',icon:'🧘',desc:'Half-kneel, tuck your pelvis slightly, and gently shift your hips forward.',duration:30,type:'sides'},{name:'Chest Opener',icon:'🙆',desc:'Open your chest gently while keeping your shoulders relaxed.',duration:35,type:'single'},{name:'Hamstring Stretch',icon:'🦵',desc:'Extend one leg and hinge forward with a long neutral back.',duration:30,type:'sides'},{name:'Child’s Pose',icon:'🌿',desc:'Sit your hips toward your heels and reach your arms forward.',duration:40,type:'single'}];
const $=id=>document.getElementById(id);let exercises=JSON.parse(localStorage.getItem('stretch_exercises')||'null')||DEFAULTS;let idx=0,states=[],running=false,tick=null;
function saveExercises(){localStorage.setItem('stretch_exercises',JSON.stringify(exercises))}function todayKey(){return new Date().toLocaleDateString('en-CA')}function getStats(){return{streak:Number(localStorage.getItem('stretch_streak')||0),xp:Number(localStorage.getItem('stretch_xp')||0),last:localStorage.getItem('stretch_last_complete')||''}}function setStats(s){localStorage.setItem('stretch_streak',String(s.streak));localStorage.setItem('stretch_xp',String(s.xp));localStorage.setItem('stretch_last_complete',s.last||'')}function refreshStats(){const s=getStats();$('streak').textContent=s.streak;$('xp').textContent=s.xp;$('status').textContent=s.last===todayKey()?'Completed today ✓':'Not completed yet'}function resetStates(){states=exercises.map(e=>({complete:false,phase:e.type==='sides'?'left':'single',left:e.duration,started:false}))}function updateSummary(){const sec=exercises.reduce((n,e)=>n+e.duration*(e.type==='sides'?2:1),0);$('minutes').textContent=Math.max(1,Math.round(sec/60));$('total').textContent=exercises.length;renderPreview()}function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function renderPreview(){const p=$('previewPanel');p.innerHTML='';exercises.forEach(e=>{const row=document.createElement('div');row.className='preview-row';row.innerHTML=`<div class="preview-icon">${e.icon||'🧘'}</div><div><b>${escapeHtml(e.name)}</b><div class="muted small">${e.type==='sides'?e.duration+' sec per side':e.duration+' sec'}</div></div>`;p.appendChild(row)})}function stop(){running=false;if(tick){clearInterval(tick);tick=null}if($('pause'))$('pause').textContent='Resume'}function showMain(view){stop();$('routineView').classList.add('hidden');$('editorView').classList.add('hidden');$('homeView').classList.toggle('hidden',view!=='home');$('settingsView').classList.toggle('hidden',view!=='settings');$('tabs').classList.remove('hidden');$('homeTab').classList.toggle('active',view==='home');$('settingsTab').classList.toggle('active',view==='settings')}
function renderRoutine(){const e=exercises[idx],s=states[idx];$('step').textContent=idx+1;$('progress').style.width=((idx+1)/exercises.length*100)+'%';$('exerciseIcon').textContent=e.icon||'🧘';$('exerciseName').textContent=e.name;$('exerciseDesc').textContent=e.desc;
const next=exercises[idx+1];
if(next){
  $('upNextCard').classList.remove('hidden');
  $('nextStretchIcon').textContent=next.icon||'🧘';
  $('nextStretchName').textContent=next.name;
}else{
  $('upNextCard').classList.add('hidden');
}
$('readyPanel').classList.add('hidden');$('timerPanel').classList.add('hidden');$('completePanel').classList.add('hidden');if(s.complete){$('completePanel').classList.remove('hidden');$('nextExercise').textContent=idx===exercises.length-1?'Finish routine':'Next stretch →';return}if(!s.started){$('readyPanel').classList.remove('hidden');const label=e.type==='sides'?(s.phase==='left'?'left side':'right side'):'stretch';$('readyTitle').textContent='Ready for '+label+'?';$('startPhase').textContent='Start '+label;return}$('timerPanel').classList.remove('hidden');$('sideLabel').textContent=e.type==='sides'?s.phase.toUpperCase()+' SIDE':'STRETCH';$('timer').textContent=s.left;$('pause').textContent=running?'Pause':'Resume'}function startTimer(){stop();const s=states[idx];if(s.complete)return;running=true;$('pause').textContent='Pause';tick=setInterval(()=>{s.left=Math.max(0,s.left-1);$('timer').textContent=s.left;if(s.left===0)phaseDone()},1000)}function phaseDone(){stop();const e=exercises[idx],s=states[idx];if(e.type==='sides'&&s.phase==='left'){s.phase='right';s.left=e.duration;s.started=false;renderRoutine();return}s.complete=true;s.started=false;renderRoutine()}
function throwConfetti(){const wrap=$('confetti');wrap.innerHTML='';const colors=['#111827','#2563eb','#16a34a','#f59e0b','#db2777'];for(let i=0;i<65;i++){const p=document.createElement('div');p.className='piece';p.style.left=Math.random()*100+'%';p.style.top=(-20-Math.random()*180)+'px';p.style.background=colors[i%colors.length];p.style.animationDelay=Math.random()*.35+'s';wrap.appendChild(p)}setTimeout(()=>wrap.innerHTML='',1900)}function finishRoutine(){stop();throwConfetti();const s=getStats(),today=todayKey();if(s.last!==today){s.streak+=1;s.xp+=40;s.last=today;setStats(s)}refreshStats();setTimeout(()=>{resetStates();idx=0;showMain('home')},1400)}
function renderEditor(){const list=$('editorList');list.innerHTML='';exercises.forEach((e,i)=>{const card=document.createElement('div');card.className='editor-card';card.innerHTML=`<div class="grid2"><label>Icon / emoji<input data-field="icon" data-i="${i}" value="${escapeHtml(e.icon)}"></label><label>Stretch name<input data-field="name" data-i="${i}" value="${escapeHtml(e.name)}"></label></div><div class="grid2" style="margin-top:10px"><label>Seconds<input data-field="duration" data-i="${i}" type="number" min="5" max="300" value="${e.duration}"></label><label>Type<select data-field="type" data-i="${i}"><option value="single" ${e.type==='single'?'selected':''}>Single</option><option value="sides" ${e.type==='sides'?'selected':''}>Left + right</option></select></label></div><label style="margin-top:10px">Description<textarea data-field="desc" data-i="${i}" rows="3">${escapeHtml(e.desc)}</textarea></label><button class="btn danger" data-remove="${i}" style="margin-top:10px">Remove stretch</button>`;list.appendChild(card)});list.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('change',ev=>{const i=Number(ev.target.dataset.i),f=ev.target.dataset.field;exercises[i][f]=f==='duration'?Math.max(5,Math.min(300,Number(ev.target.value)||30)):ev.target.value;saveExercises();resetStates();updateSummary();renderEditor()}));list.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{exercises.splice(Number(b.dataset.remove),1);if(!exercises.length)exercises.push({name:'New Stretch',icon:'🧘',desc:'Add instructions here.',duration:30,type:'single'});saveExercises();resetStates();updateSummary();renderEditor()}))}
$('homeTab').onclick=()=>showMain('home');$('settingsTab').onclick=()=>showMain('settings');$('previewButton').onclick=()=>{const hidden=$('previewPanel').classList.toggle('hidden');$('previewButton').textContent=hidden?'Preview stretches':'Hide preview'};$('startRoutine').onclick=()=>{resetStates();idx=0;$('previewPanel').classList.add('hidden');$('previewButton').textContent='Preview stretches';$('tabs').classList.add('hidden');$('homeView').classList.add('hidden');$('settingsView').classList.add('hidden');$('routineView').classList.remove('hidden');renderRoutine()};$('startPhase').onclick=()=>{states[idx].started=true;renderRoutine();startTimer()};$('pause').onclick=()=>running?stop():startTimer();$('nextExercise').onclick=()=>{if(idx===exercises.length-1){finishRoutine();return}stop();idx++;renderRoutine()};$('finishRoutine').onclick=finishRoutine;$('exitRoutine').onclick=()=>showMain('home');$('editRoutine').onclick=()=>{$('tabs').classList.add('hidden');$('settingsView').classList.add('hidden');$('editorView').classList.remove('hidden');renderEditor()};$('backSettings').onclick=()=>showMain('settings');$('addExercise').onclick=()=>{exercises.push({name:'New Stretch',icon:'🧘',desc:'Describe how to perform this stretch.',duration:30,type:'single'});saveExercises();resetStates();updateSummary();renderEditor()};$('reminderTime').value=localStorage.getItem('stretch_reminder_time')||'20:00';$('reminderTime').onchange=()=>localStorage.setItem('stretch_reminder_time',$('reminderTime').value);
async function registerSW(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch(e){}}}async function updateNotificationStatus(){const supported='Notification'in window&&'serviceWorker'in navigator;if(!supported){$('notificationStatus').textContent='Notifications are not supported in this browser.';return}$('notificationStatus').textContent='Permission: '+Notification.permission}$('enableNotifications').onclick=async()=>{if(!('Notification'in window)){updateNotificationStatus();return}try{await Notification.requestPermission()}catch(e){}updateNotificationStatus()};$('testNotification').onclick=async()=>{if(Notification.permission!=='granted'){alert('Enable notifications first.');return}const reg=await navigator.serviceWorker.ready;reg.showNotification('Time to stretch 🧘',{body:'Your Daily Stretch app is ready.',icon:'./icons/icon-192.png',badge:'./icons/icon-192.png'})};registerSW();resetStates();updateSummary();refreshStats();updateNotificationStatus();
document.addEventListener('gesturestart', e => e.preventDefault(), {passive:false});
document.addEventListener('gesturechange', e => e.preventDefault(), {passive:false});
document.addEventListener('gestureend', e => e.preventDefault(), {passive:false});
